#!/bin/bash

#-- VARIABLE source
sourceDIR[ 1]='../EUROPE_STS'
sourceDIR[ 2]='../EUROPE_STS'
sourceDIR[ 3]='../EUROPE_STS'
sourceDIR[ 4]='../EUROPE_STS'

#-- VARIABLE RegCM name
varalica[ 1]='t2avg'
varalica[ 2]='t2max'
varalica[ 3]='t2min'
varalica[ 4]='pcpavg'



#-------- Global attributes
	Conventions="CF-1.4"
	contact="ivan.guettler@cirus.dhz.hr"
	creation_date="2014-07-15"
	experiment="Evaluation run with reanalysis forcing"
	experiment_id="evaluation"
	driving_experiment="ECMWF-ERAINT, evaluation, r1i1p1"
	driving_model_id="ECMWF-ERAINT"
	driving_model_ensemble_member="r1i1p1"
	driving_experiment_name="evaluation"
	institution="Meteorological and Hydrological Service of Croatia"
	institute_id="DHMZ"
	model_id="DHMZ-RegCM4-2"
	rcm_version_id="v1"
	project_id="CORDEX"
	CORDEX_domain="EUR-44"
	product="output"
	references="http://gforge.ictp.it/gf/project/regcm/"
#-------- Global attributes
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#---------- Projection stuff
        projection_type="char"
        projection_name="Lambert_Conformal"
        projection_grid_mapping_name="lambert_conformal_conic" 
        projection_standard_parallel1=30.0
        projection_standard_parallel2=65.0
        projection_longitude_of_central_meridian=9.75
        projection_latitude_of_projection_origin=49.68

	x_type="double"
	x_name="x"
	x_units="km"
	x_long_name="x coordinate of projection"
	x_standard_name="projection_x_coordinate"
	x_axis="X"

	y_type="double"
	y_name="y"
	y_units="km"
	y_long_name="y coordinate of projection"
	y_standard_name="projection_y_coordinate"
	y_axis="Y"

	lon_type="double"
	lon_name="lon"
	lon_standard_name="longitude"
	lon_long_name="longitude"
	lon_units="degrees_east"

	lat_type="double"
	lat_name="lat"
	lat_standard_name="latitude"
	lat_long_name="latitude"
	lat_units="degrees_north"
#---------- Projection stuff
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#----------- Time stuff
        time_start_date='1949-12-01'
        time_start_hour='00:00'
        time_start='1949-12-01 00:00'
        time_start_unit=day
        time_long_name="time"
        time_standard_name="time"
        time_axis="T"
        time_units="days since 1949-12-01T00:00:00Z"
        time_calendar="proleptic_gregorian"
        time_bounds="time_bnds"
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------

#======================================================================================
#======================================================================================
#======================================================================================

#This is needed for spliting files in HadGEM HIST
    DAYstrt[1]=19700101
        DAYendi[1]=19701230
            DAYstrt[2]=19710101
                DAYendi[2]=19751230
                    DAYstrt[3]=19760101
                        DAYendi[3]=19801230
                            DAYstrt[4]=19810101
                                DAYendi[4]=19851230
                                    DAYstrt[5]=19860101
                                        DAYendi[5]=19901230
                                            DAYstrt[6]=19910101
                                                DAYendi[6]=19951230
                                                    DAYstrt[7]=19960101
                                                        DAYendi[7]=20001230
                                                            DAYstrt[8]=20010101
                                                                DAYendi[8]=20051130
#Datumi koji su mi potrebni za ispravno definiranje intervala
    DAYendX[1]=19710101 #cdo uzima unutar intervala pa moramo prilagoditi ovako
        DAYendX[2]=19760101
            DAYendX[3]=19810101
                DAYendX[4]=19860101
                    DAYendX[5]=19910101
                        DAYendX[6]=19960101
                            DAYendX[7]=20010101
                                DAYendX[8]=20051201

#Datumi koji ce pisati u nazivu datoteke

    MONstrt[1]=197001
        MONendi[1]=197012
            MONstrt[2]=197101
                MONendi[2]=198012
                    MONstrt[3]=198101
                        MONendi[3]=199012
                            MONstrt[4]=199101
                                MONendi[4]=200012
                                    MONstrt[5]=200101
                                        MONendi[5]=200511

#Datumi koji su mi potrebni za ispravno definiranje intervala
    MONstrX[1]=19700101
        MONendX[1]=19710101
            MONstrX[2]=19710101
                MONendX[2]=19810101
                    MONstrX[3]=19810101
                        MONendX[3]=19910101
                            MONstrX[4]=19910101
                                MONendX[4]=20010101
                                    MONstrX[5]=20010101
                                       MONendX[5]=20051201

#Datumi koji su mi potrebni za ispravno definiranje intervala
#    YEARSforMON[1]='1970'
#        YEARSforMON[2]='1971,1972,1973,1974,1975,1976,1977,1978,1979,1980'
#            YEARSforMON[3]='1981,1982,1983,1984,1985,1986,1987,1988,1989,1990'
#                YEARSforMON[4]='1991,1992,1993,1994,1995,1996,1997,1998,1999,2000'
#                    YEARSforMON[5]='2001,2002,2003,2004,2005'

#Datumi koji ce pisati u nazivu datoteke
    SEMstrt[1]=197003
        SEMendi[1]=197011
            SEMstrt[2]=197012
                SEMendi[2]=198011
                    SEMstrt[3]=198012
                        SEMendi[3]=199011
                            SEMstrt[4]=199012
                                SEMendi[4]=200011
                                    SEMstrt[5]=200012
                                        SEMendi[5]=200511

#Datumi koji su mi potrebni za ispravno definiranje intervala
    SEMstrX[1]=19700530
        SEMendX[1]=19701230
            SEMstrX[2]=19710230
                SEMendX[2]=19801230
                    SEMstrX[3]=19810230
                        SEMendX[3]=19901230
                            SEMstrX[4]=19910230
                                SEMendX[4]=20001230
                                    SEMstrX[5]=20010230
                                       SEMendX[5]=20051130

#======================================================================================
#======================================================================================
#======================================================================================
