#!/bin/bash

#-- Years to ingest
	STARTyyy=1989
	  ENDyyy=2008
#-- Region to consider
 #   For this exp grid is 573 x 573 cell. Buffer zone includes 11 cells. After removing the buffer zone, the grid includes 551 x 551 cells
 #   Important: nco considers indexes by default 0:550 (not 1:551). To use 1:551 index counting in nco one can select -F.
 #   NXstart=12 -1
 #   NXendic=562-1
 #   NYstart=12 -1
 #   NYendic=562-1

    NXstart=11
    NXendic=561
    NYstart=11
    NYendic=561

#-- Details of the regular grid are from "Table 2 Regular CORDEX grids" in "CORDEX Archive Design" document, version 3.1
    RegularGrid=./CORDEX_metadata_01_grid.txt

#-- VARIABLE source DIR
sourceDIR[ 1]='/home1/regcm/DISK_zemlja/CORDEX/TEST/ERAInterim12km/postproc/FILES_SRF/DM'
sourceDIR[ 2]=''
sourceDIR[ 3]=''
sourceDIR[ 4]='/home1/regcm/DISK_zemlja/CORDEX/TEST/ERAInterim12km/postproc/FILES_SRF/DM'
sourceDIR[ 5]=''
sourceDIR[ 9]='/home1/regcm/DISK_zemlja/CORDEX/TEST/ERAInterim12km/postproc/SRF_CALCULATED/DATA_wind10m/DM'
sourceDIR[10]=''
sourceDIR[32]='/home1/regcm/DISK_zemlja/CORDEX/TEST/ERAInterim12km/postproc/SRF_CALCULATED/DATA_wind10m/DM'
sourceDIR[33]='/home1/regcm/DISK_zemlja/CORDEX/TEST/ERAInterim12km/postproc/SRF_CALCULATED/DATA_wind10m/DM'
sourceDIR[37]=''
sourceDIR[38]=''
#-- VARIABLE source FILE
sourceFILE[ 1]='EUROPE_tas'
sourceFILE[ 2]='EUROPE_STS'
sourceFILE[ 3]='EUROPE_STS'
sourceFILE[ 4]='EUROPE_pr'
sourceFILE[ 5]='EUROPE_STS'
sourceFILE[ 9]='EUROPE_rotatedWind10m'
sourceFILE[10]='EUROPE_STS'
sourceFILE[32]='EUROPE_rotatedWind10m'
sourceFILE[33]='EUROPE_rotatedWind10m'
sourceFILE[37]='EUROPE_tg'
sourceFILE[38]='EUROPE_zpbl'
#-- VARIABLE RegCM name
varalica[ 1]='tas'
varalica[ 2]=''
varalica[ 3]=''
varalica[ 4]='pr'
varalica[ 5]=''
varalica[ 9]='sfcwind'
varalica[10]=''
varalica[32]='uas'
varalica[33]='vas'
varalica[37]=''
varalica[38]=''

#-------- Global attributes
	Conventions="CF-1.4"
	contact="ivan.guettler@cirus.dhz.hr"
	creation_date="2015-04-15"
	experiment="Evaluation run with reanalysis forcing"
	experiment_id="evaluation"
	driving_experiment="ECMWF-ERAINT, evaluation, r1i1p1"
	driving_model_id="ECMWF-ERAINT"
	driving_model_ensemble_member="r1i1p1"
	driving_experiment_name="evaluation"
	institution="Meteorological and Hydrological Service of Croatia"
	institute_id="DHMZ"
	model_id="DHMZ-RegCM4-2"
	rcm_version_id="v1"
	project_id="CORDEX"
	CORDEX_domain="EUR-11"
        CORDEX_domain_i="EUR-11i"
	product="output"
	references="http://gforge.ictp.it/gf/project/regcm/"
#-------- Global attributes
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#---------- Projection stuff
        projection_type="char"
        projection_name="Lambert_Conformal"
        projection_grid_mapping_name="lambert_conformal_conic" 
        projection_standard_parallel1=30.0
        projection_standard_parallel2=65.0
        projection_longitude_of_central_meridian=9.75
        projection_latitude_of_projection_origin=49.68

	x_type="double"
	x_name="x"
	x_units="km"
	x_long_name="x coordinate of projection"
	x_standard_name="projection_x_coordinate"
	x_axis="X"

	y_type="double"
	y_name="y"
	y_units="km"
	y_long_name="y coordinate of projection"
	y_standard_name="projection_y_coordinate"
	y_axis="Y"

	lon_type="double"
	lon_name="lon"
	lon_standard_name="longitude"
	lon_long_name="longitude"
	lon_units="degrees_east"

	lat_type="double"
	lat_name="lat"
	lat_standard_name="latitude"
	lat_long_name="latitude"
	lat_units="degrees_north"
#---------- Projection stuff
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#----------- Time stuff
        time_start_date='1949-12-01'
        time_start_hour='00:00'
        time_start='1949-12-01 00:00'
        time_start_unit=day
        time_long_name="time"
        time_standard_name="time"
        time_axis="T"
        time_units="days since 1949-12-01 00:00:00Z"
        time_calendar="proleptic_gregorian"
        time_bounds="time_bnds"
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------

