#!/bin/bash
# BASED ON 21 FEB 2014 Version 3.1
# Ivan Guettler: 07-07-2014
# Ivan Guettler: 17-11-2014

MONTHS=( 01 02 03 04 05 06 07 08 09 10 11 12 );

#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#--- output variable name
name[ 1]='tas'
name[ 2]='tasmax'
name[ 3]='tasmin'
name[ 4]='pr'
name[ 5]='ps'
name[ 6]='psl'
name[ 7]='huss'
name[ 8]='hurs'
name[ 9]='sfcWind'
name[10]='sfcWindmax'
name[11]='clt'
name[12]='sund'
name[13]='rsds'
name[14]='rlds'
name[15]='hfls'
name[16]='hfss'
name[17]='rsus'
name[18]='rlus'
name[19]='evspsbl'
name[20]='evspsblpot'
name[21]='mfrso'
name[22]='mrros'
name[23]='mrro'
name[24]='mrso'
name[25]='snw'
name[26]='snm'
name[27]='prhmax'
name[28]='prc'
name[29]='rlut'
name[30]='rsdt'
name[31]='rsut'
name[32]='uas'
name[33]='vas'
name[34]='wsgsmax'
name[35]='tauu'
name[36]='tauv'
name[37]='ts'
name[38]='zmla'
name[39]='prw'
name[40]='clwvi'
name[41]='clivi'
name[42]='ua850'
name[43]='va850'
name[44]='ta850'
name[45]='hus850'
name[46]='ua500'
name[47]='va500'
name[48]='zg500'
name[49]='ta500'
name[50]='ua200'
name[51]='va200'
name[52]='ta200'
name[53]='zg200'
name[54]='clh'
name[55]='clm'
name[56]='cll'
name[57]='snc'
name[58]='snd'
name[59]='sic'
name[60]='prsn'
name[61]='areacella'
name[62]='orog' 
name[63]='sftls'
name[64]='sftlf'
name[65]='sftgif'
name[66]='mrsofc'
name[67]='rootd'
#--- output variable name
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#---- VARIABLE long_name
long_name[ 1]='Near-Surface Air Temperature'
long_name[ 2]='Daily Maximum Near-Surface Air Temperature'
long_name[ 3]='Daily Minimum Near-Surface Air Temperature'
long_name[ 4]='Precipitation'
long_name[ 5]='Surface Air Pressure'
long_name[ 6]='Sea Level Pressure'
long_name[ 7]='Near-Surface Specific Humidity'
long_name[ 8]='Near-Surface Relative Humidity'
long_name[ 9]='Near-Surface Wind Speed'
long_name[10]='Daily Maximum Near-Surface Wind Speed'
long_name[11]='Total Cloud Fraction'
long_name[12]='Duration Of Sunshine'
long_name[13]='Surface Downwelling Shortwave Radiation'
long_name[14]='Surface Downwelling Longwave Radiation'
long_name[15]='Surface Upward Latent Heat Flux'
long_name[16]='Surface Upward Sensible Heat Flux'
long_name[17]='Surface Upwelling Shortwave Radiation'
long_name[18]='Surface Upwelling Longwave Radiation'
long_name[19]='Evaporation'
long_name[20]='Potential Evapotransiration'
long_name[21]='Soil Frozen Water Content'
long_name[22]='Surface Runoff'
long_name[23]='Total Runoff'
long_name[24]='Total Soil Moisture'
long_name[25]='Surface Snow Amount'
long_name[26]='Surface Snow Melt'
long_name[27]='Daily Maximum Hourly Precipitation Rate'
long_name[28]='Convective Precipitation'
long_name[29]='TOA Outgoing Longwave Radiation'
long_name[30]='TOA Incident Shortwave Radiation'
long_name[31]='TOA Outgoing Shortwave Radiation'
long_name[32]='Eastward Near-Surface Wind'
long_name[33]='Northward Near-Surface Wind'
long_name[34]='Daily Maximum Near-Surface Wind Speed of Gust'
long_name[35]='Surface Downward Eastward Wind Stress'
long_name[36]='Surface Downward Northward Wind Stress'
long_name[37]='Surface Temperature'
long_name[38]='Height of Boundary Layer'
long_name[39]='Water Vapor Path'
long_name[40]='Condensed Water Path'
long_name[41]='Ice Water Path'
long_name[42]='Eastward Wind'
long_name[43]='Northward Wind'
long_name[44]='Air Temperature'
long_name[45]='Specific Humidity'
long_name[46]='Eastward Wind'
long_name[47]='Northward Wind'
long_name[48]='Geopotential Height'
long_name[49]='Air Temperature'
long_name[50]='Eastward Wind'
long_name[51]='Northward Wind'
long_name[52]='Air Temperature'
long_name[53]='Geopotential Height'
long_name[54]='High Level Cloud Fraction'
long_name[55]='Medium Level Cloud Fraction'
long_name[56]='Low Level Cloud Fraction'
long_name[57]='Snow Area Fraction'
long_name[58]='Snow Depth'
long_name[59]='Sea Ice Area Fraction'
long_name[60]='Snowfall Flux'
long_name[61]='Atmosphere Grid-Cell Area'
long_name[62]='Surface Altitude'  
long_name[63]='Land Area Fraction'
long_name[64]='Fraction of Grid Cell Covered with Glacier'
long_name[65]='Capacity of Soil to Store Water'
long_name[66]='Maximum Root Depth'
#---- VARIABLE long_name
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#----- VARIABLE standard_name
stand_name[ 1]='air_temperature'
stand_name[ 2]='air_temperature'
stand_name[ 3]='air_temperature'
stand_name[ 4]='precipitation_flux'
stand_name[ 5]='surface_air_pressure'
stand_name[ 6]='air_pressure_at_sea_level'
stand_name[ 7]='specific_humidity'
stand_name[ 8]='relative_humidity'
stand_name[ 9]='wind_speed'
stand_name[10]='wind_speed'
stand_name[11]='cloud_area_fraction'
stand_name[12]='duration_of_sunshine'
stand_name[13]='surface_downwelling_shortwave_flux_in_air'
stand_name[14]='surface_downwelling_longwave_flux_in_air'
stand_name[15]='surface_upward_latent_heat_flux'
stand_name[16]='surface_upward_sensible_heat_flux'
stand_name[17]='surface_upwelling_shortwave_flux_in_air'
stand_name[18]='surface_upwelling_longwave_flux_in_air'
stand_name[19]='water_evaporation_flux'
stand_name[20]='water_potential_evaporation_flux'
stand_name[21]='soil_frozen_water_content'
stand_name[22]='surface_runoff_flux'
stand_name[23]='runoff_flux'
stand_name[24]='soil_moisture_content'
stand_name[25]='surface_snow_amount'
stand_name[26]='surface_snow_melt_flux'
stand_name[27]='precipitation_flux'
stand_name[28]='convective_precipitation_flux'
stand_name[29]='toa_outgoing_longwave_flux'
stand_name[30]='toa_incoming_shortwave_flux'
stand_name[31]='toa_outgoing_shortwave_flux'
stand_name[32]='eastward_wind'
stand_name[33]='northward_wind'
stand_name[34]='wind_speed_of_gust'
stand_name[35]='surface_downward_eastward_stress'
stand_name[36]='surface_downward_northward_stress'
stand_name[37]='surface_temperature'
stand_name[38]='atmosphere_boundary_layer_thickness'
stand_name[39]='atmosphere_water_vapor_content'
stand_name[40]='atmosphere_cloud_condensed_water_content'
stand_name[41]='atmosphere_cloud_ice_content'
stand_name[42]='eastward_wind'
stand_name[43]='northward_wind'
stand_name[44]='air_temperature'
stand_name[45]='specific_humidity'
stand_name[46]='eastward_wind'
stand_name[47]='northward_wind'
stand_name[48]='geopotential_height'
stand_name[49]='air_temperature'
stand_name[50]='eastward_wind'
stand_name[51]='northward_wind'
stand_name[52]='air_temperature'
stand_name[53]='geopotential_height'
stand_name[54]='cloud_area_fraction_in_atmosphere_layer'
stand_name[55]='cloud_area_fraction_in_atmosphere_layer'
stand_name[56]='cloud_area_fraction_in_atmosphere_layer'
stand_name[57]='surface_snow_area_fraction'
stand_name[58]='surface_snow_thickness'
stand_name[59]='sea_ice_fraction'
stand_name[60]='snowfall_flux'
stand_name[61]='cell_area'   
stand_name[62]='surface_altitude' 
stand_name[63]='land_area_fraction'  
stand_name[64]='land_ice_area_fraction' 
stand_name[65]='soil_moisture_content_at_field_capacity'  
stand_name[66]='root_depth'
#----- VARIABLE standard_name
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#------ Units
units[ 1]='K'
units[ 2]='K'
units[ 3]='K'
units[ 4]='kg m-2 s-1'
units[ 5]='Pa'
units[ 6]='Pa'
units[ 7]='1'
units[ 8]='%'
units[ 9]='m s-1'
units[10]='m s-1'
units[11]='%'
units[12]='s'
units[13]='W m-2'
units[14]='W m-2'
units[15]='W m-2'
units[16]='W m-2'
units[17]='W m-2'
units[18]='W m-2'
units[19]='kg m-2 s-1'
units[20]='kg m-2 s-1'
units[21]='kg m-2'
units[22]='kg m-2 s-1'
units[23]='kg m-2 s-1'
units[24]='kg m-2'
units[25]='kg m-2'
units[26]='kg m-2 s-1'
units[27]='kg m-2 s-1'
units[28]='kg m-2 s-1'
units[29]='W m-2'
units[30]='W m-2'
units[31]='W m-2'
units[32]='m s-1'
units[33]='m s-1'
units[34]='m s-1'
units[35]='Pa'
units[36]='Pa'
units[37]='K'
units[38]='m'
units[39]='kg m-2'
units[40]='kg m-2'
units[41]='kg m-2'
units[42]='m s-1'
units[43]='m s-1'
units[44]='K'
units[45]='1'
units[46]='m s-1'
units[47]='m s-1'
units[48]='m'
units[49]='K'
units[50]='m s-1'
units[51]='m s-1'
units[52]='K'
units[53]='m'
units[54]='%'
units[55]='%'
units[56]='%'
units[57]='%'
units[58]='m'
units[59]='%'
units[60]='kg m-2 s-1'
units[61]='m2'
units[62]='m'
units[63]='%'
units[64]='%'
units[65]='kg m-2'
units[66]='m'
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#------ Height (m/hPa)
heights[ 1]=2
heights[ 2]=2
heights[ 3]=2
heights[ 4]=0
heights[ 5]=0
heights[ 6]=0
heights[ 7]=2
heights[ 8]=0
heights[ 9]=10
heights[10]=10
heights[11]=0
heights[12]=0
heights[13]=0
heights[14]=0
heights[15]=0
heights[16]=0
heights[17]=0
heights[18]=0
heights[19]=0
heights[20]=0
heights[21]=0
heights[22]=0
heights[23]=0
heights[24]=0
heights[25]=0
heights[26]=0
heights[27]=0
heights[28]=0
heights[29]=0
heights[30]=0
heights[31]=10
heights[32]=10
heights[33]=0
heights[34]=0
heights[35]=0
heights[36]=0
heights[37]=0
heights[38]=0
heights[39]=0
heights[40]=0
heights[41]=850
heights[42]=850
heights[43]=850
heights[44]=850
heights[45]=500
heights[46]=500
heights[47]=500
heights[48]=500
heights[49]=200
heights[50]=200
heights[51]=200
heights[52]=200
heights[53]=0
heights[54]=0
heights[55]=0
heights[56]=0
heights[57]=0
heights[58]=0
heights[59]=0
heights[60]=0
heights[61]=0
heights[62]=0
heights[63]=0
heights[64]=0
heights[65]=0
heights[66]=0
#------ Units
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#------- cellMethod DM
cellMethodDM[ 1]='time: mean'
cellMethodDM[ 2]='time: maximum'
cellMethodDM[ 3]='time: minimum'
cellMethodDM[ 4]='time: mean'
cellMethodDM[ 5]='time: mean'
cellMethodDM[ 6]='time: mean'
cellMethodDM[ 7]='time: mean'
cellMethodDM[ 8]='time: mean'
cellMethodDM[ 9]='time: mean'
cellMethodDM[10]='time: maximum'
cellMethodDM[11]='time: mean'
cellMethodDM[12]='time: sum'
cellMethodDM[13]='time: mean'
cellMethodDM[14]='time: mean'
cellMethodDM[15]='time: mean'
cellMethodDM[16]='time: mean'
cellMethodDM[17]='time: mean'
cellMethodDM[18]='time: mean'
cellMethodDM[19]='time: mean'
cellMethodDM[20]='time: mean'
cellMethodDM[21]='time: mean area: mean where land'
cellMethodDM[22]='time: mean area: mean where land'
cellMethodDM[23]='time: mean area: mean where land'
cellMethodDM[24]='time: mean area: mean where land'
cellMethodDM[25]='time: mean area: mean where land'
cellMethodDM[26]='time: mean area: mean where land'
cellMethodDM[27]='time: maximum'
cellMethodDM[28]='time: mean'
cellMethodDM[29]='time: mean' 
cellMethodDM[30]='time: mean' 
cellMethodDM[31]='time: mean' 
cellMethodDM[32]='time: mean'
cellMethodDM[33]='time: mean'
cellMethodDM[34]='time: maximum'
cellMethodDM[35]='time: mean' 
cellMethodDM[36]='time: mean' 
cellMethodDM[37]='time: mean'
cellMethodDM[38]='time: mean'
cellMethodDM[39]='time: mean'
cellMethodDM[40]='time: mean'
cellMethodDM[41]='time: mean'
cellMethodDM[42]='time: mean'
cellMethodDM[43]='time: mean'
cellMethodDM[44]='time: mean'
cellMethodDM[45]='time: mean'
cellMethodDM[46]='time: mean'
cellMethodDM[47]='time: mean'
cellMethodDM[48]='time: mean'
cellMethodDM[49]='time: mean'
cellMethodDM[50]='time: mean'
cellMethodDM[51]='time: mean'
cellMethodDM[52]='time: mean'
cellMethodDM[53]='time: mean'
cellMethodDM[54]='time: mean'
cellMethodDM[55]='time: mean'
cellMethodDM[56]='time: mean'
cellMethodDM[57]='time: mean'
cellMethodDM[58]='time: mean area: mean where land'
cellMethodDM[59]='time: mean'
cellMethodDM[60]='time: mean'
#------- cellMethod DM
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#------- cellMethod MM&SM
cellMethodMMSM[ 1]='time: mean'
cellMethodMMSM[ 2]='time: maximum within days time: mean over days'
cellMethodMMSM[ 3]='time: minimum within days time: mean over days'
cellMethodMMSM[ 4]='time: mean'
cellMethodMMSM[ 5]='time: mean'
cellMethodMMSM[ 6]='time: mean'
cellMethodMMSM[ 7]='time: mean'
cellMethodMMSM[ 8]='time: mean'
cellMethodMMSM[ 9]='time: mean'
cellMethodMMSM[10]='time: maximum within days time: mean over days'
cellMethodMMSM[11]='time: mean'
cellMethodMMSM[12]='time: sum within days time: mean over days'
cellMethodMMSM[13]='time: mean'
cellMethodMMSM[14]='time: mean'
cellMethodMMSM[15]='time: mean'
cellMethodMMSM[16]='time: mean'
cellMethodMMSM[17]='time: mean'
cellMethodMMSM[18]='time: mean'
cellMethodMMSM[19]='time: mean'
cellMethodMMSM[20]='time: mean'
cellMethodMMSM[21]='time: mean area: mean where land'
cellMethodMMSM[22]='time: mean area: mean where land'
cellMethodMMSM[23]='time: mean area: mean where land'
cellMethodMMSM[24]='time: mean area: mean where land'
cellMethodMMSM[25]='time: mean area: mean where land'
cellMethodMMSM[26]='time: mean area: mean where land'
cellMethodMMSM[27]='time: maximum within days time: mean over days'
cellMethodMMSM[28]='time: mean'
cellMethodMMSM[29]='time: mean' 
cellMethodMMSM[30]='time: mean' 
cellMethodMMSM[31]='time: mean' 
cellMethodMMSM[32]='time: mean'
cellMethodMMSM[33]='time: mean'
cellMethodMMSM[34]='time: maximum within days time: mean over days'
cellMethodMMSM[35]='time: mean' 
cellMethodMMSM[36]='time: mean' 
cellMethodMMSM[37]='time: mean'
cellMethodMMSM[38]='time: mean'
cellMethodMMSM[39]='time: mean'
cellMethodMMSM[40]='time: mean'
cellMethodMMSM[41]='time: mean'
cellMethodMMSM[42]='time: mean'
cellMethodMMSM[43]='time: mean'
cellMethodMMSM[44]='time: mean'
cellMethodMMSM[45]='time: mean'
cellMethodMMSM[46]='time: mean'
cellMethodMMSM[47]='time: mean'
cellMethodMMSM[48]='time: mean'
cellMethodMMSM[49]='time: mean'
cellMethodMMSM[50]='time: mean'
cellMethodMMSM[51]='time: mean'
cellMethodMMSM[52]='time: mean'
cellMethodMMSM[53]='time: mean'
cellMethodMMSM[54]='time: mean'
cellMethodMMSM[55]='time: mean'
cellMethodMMSM[56]='time: mean'
cellMethodMMSM[57]='time: mean'
cellMethodMMSM[58]='time: mean area: mean where land'
cellMethodMMSM[59]='time: mean'
cellMethodMMSM[60]='time: mean'
#------- cellMethod DM
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#------- frequency
frequency[1]='day'
frequency[2]='mon'
frequency[3]='sem'
frequency[4]='fx'
frequency[5]='3hr'
frequency[6]='6hr'
#------- frequency
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#--------- Single value variables
	#height=2 m
	H2_value=2
	H2_type="double height"
	H2_longname="height"
	H2_standardname="height"
	H2_units="m"
	H2_positive="up"
	H2_axis="Z"

	#height=10 m
	H10_value=10
	H10_type="double height"
	H10_longname="height"
	H10_standardname="height"
	H10_units="m"
	H10_positive="up"
	H10_axis="Z"

	#plev=850 00,500 00,200 00
	P_type="double plev"
	P_longname="pressure level"
	P_standardname="air_pressure"
	P_units="Pa"
	P_positive="down"
	P_axis="Z"
#--------- Single value variables

